export const styles = {
  shell: {
    minHeight: "100vh",
    background: "var(--color-background-tertiary)",
    fontFamily: "var(--font-sans)",
  },
  nav: {
    background: "var(--color-background-primary)",
    borderBottom: "0.5px solid var(--color-border-tertiary)",
    padding: "0 24px",
    display: "flex",
    alignItems: "center",
    gap: 32,
    height: 52,
  },
  logo: {
    fontWeight: 500,
    fontSize: 16,
    color: "var(--color-text-primary)",
    letterSpacing: "-0.01em",
  },
  navLinks: {
    display: "flex",
    gap: 4,
  },
  navLink: {
    padding: "6px 12px",
    borderRadius: "var(--border-radius-md)",
    fontSize: 14,
    color: "var(--color-text-secondary)",
    textDecoration: "none",
  },
  navLinkActive: {
    color: "var(--color-text-primary)",
    background: "var(--color-background-secondary)",
    fontWeight: 500,
  },
  main: {
    maxWidth: 520,
    margin: "40px auto",
    padding: "0 16px",
  },
  page: {
    background: "var(--color-background-primary)",
    borderRadius: "var(--border-radius-lg)",
    border: "0.5px solid var(--color-border-tertiary)",
    padding: "24px",
    display: "flex",
    flexDirection: "column",
    gap: 16,
  },
  pageTitle: {
    margin: 0,
    fontSize: 18,
    fontWeight: 500,
    color: "var(--color-text-primary)",
  },
  field: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    flex: 1,
  },
  label: {
    fontSize: 13,
    color: "var(--color-text-secondary)",
  },
  input: {
    height: 36,
    padding: "0 10px",
    borderRadius: "var(--border-radius-md)",
    border: "0.5px solid var(--color-border-secondary)",
    background: "var(--color-background-primary)",
    color: "var(--color-text-primary)",
    fontSize: 14,
    width: "100%",
    boxSizing: "border-box",
  },
  select: {
    height: 36,
    padding: "0 8px",
    borderRadius: "var(--border-radius-md)",
    border: "0.5px solid var(--color-border-secondary)",
    background: "var(--color-background-primary)",
    color: "var(--color-text-primary)",
    fontSize: 14,
    width: "100%",
    boxSizing: "border-box",
  },
  qRow: {
    display: "flex",
    gap: 12,
    alignItems: "flex-end",
  },
  btn: {
    height: 36,
    padding: "0 16px",
    borderRadius: "var(--border-radius-md)",
    border: "0.5px solid var(--color-border-secondary)",
    background: "transparent",
    color: "var(--color-text-primary)",
    fontSize: 14,
    cursor: "pointer",
    alignSelf: "flex-start",
  },
  resultCard: {
    background: "var(--color-background-secondary)",
    borderRadius: "var(--border-radius-md)",
    padding: "16px",
  },
  badge: {
    display: "inline-block",
    fontSize: 11,
    padding: "2px 8px",
    borderRadius: "var(--border-radius-md)",
    background: "var(--color-background-info)",
    color: "var(--color-text-info)",
    fontWeight: 500,
    textTransform: "uppercase",
    letterSpacing: "0.04em",
  },
  historyRow: {
    background: "var(--color-background-secondary)",
    borderRadius: "var(--border-radius-md)",
    padding: "12px 14px",
  },
};