export const styles = {
  shell: {
    minHeight: "100vh",
    background: "linear-gradient(135deg, #f5f3ff 0%, #fff 100%)",
    fontFamily: "var(--sans)",
    paddingBottom: 40,
  },
  nav: {
    background: "var(--bg)",
    borderBottom: "1px solid var(--border)",
    boxShadow: "var(--shadow-md)",
    padding: "0 24px",
    display: "flex",
    alignItems: "center",
    gap: 32,
    height: 64,
    position: "sticky",
    top: 0,
    zIndex: 100,
  },
  logo: {
    fontWeight: 700,
    fontSize: 20,
    color: "var(--accent)",
    letterSpacing: "-0.01em",
    textDecoration: "none",
    cursor: "pointer",
  },
  navLinks: {
    display: "flex",
    gap: 8,
  },
  navLink: {
    padding: "8px 16px",
    borderRadius: "8px",
    fontSize: 14,
    fontWeight: 500,
    color: "var(--text)",
    textDecoration: "none",
    transition: "all 0.2s ease",
    cursor: "pointer",
    border: "1px solid transparent",
  },
  navLinkActive: {
    color: "var(--accent)",
    background: "var(--accent-bg)",
    border: "1px solid var(--accent-border)",
    fontWeight: 600,
  },
  main: {
    maxWidth: 600,
    margin: "40px auto",
    padding: "0 16px",
    flex: 1,
  },
  page: {
    background: "var(--bg)",
    borderRadius: "16px",
    border: "1px solid var(--border)",
    boxShadow: "var(--shadow-lg)",
    padding: "32px",
    display: "flex",
    flexDirection: "column",
    gap: 24,
  },
  pageTitle: {
    fontSize: 28,
    fontWeight: 600,
    color: "var(--text-h)",
    margin: "0 0 16px",
    textAlign: "left",
  },
  field: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    textAlign: "left",
  },
  label: {
    fontSize: 13,
    fontWeight: 600,
    color: "var(--text-h)",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
  },
  input: {
    padding: "12px 16px",
    borderRadius: "10px",
    border: "1.5px solid var(--border)",
    fontSize: 16,
    fontFamily: "inherit",
    color: "var(--text-h)",
    background: "var(--bg)",
    transition: "all 0.2s ease",
    outline: "none",
    boxSizing: "border-box",
    WebkitAppearance: "none",
    appearance: "none",
    cursor: "text",
  },
  inputFocus: {
    borderColor: "var(--accent)",
    boxShadow: "0 0 0 3px var(--accent-bg)",
    outline: "none",
  },
  select: {
    padding: "12px 16px",
    paddingRight: "36px",
    borderRadius: "10px",
    border: "1.5px solid var(--border)",
    fontSize: 16,
    fontFamily: "inherit",
    color: "var(--text-h)",
    background: "var(--bg)",
    transition: "all 0.2s ease",
    outline: "none",
    boxSizing: "border-box",
    cursor: "pointer",
    WebkitAppearance: "none",
    appearance: "none",
    backgroundImage: `url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='12' viewBox='0 0 12 12'%3E%3Cpath fill='%23aa3bff' d='M1 4l5 4 5-4'/%3E%3C/svg%3E")`,
    backgroundRepeat: "no-repeat",
    backgroundPosition: "right 12px center",
  },
  selectFocus: {
    borderColor: "var(--accent)",
    boxShadow: "0 0 0 3px var(--accent-bg)",
    outline: "none",
  },
  qRow: {
    display: "grid",
    gridTemplateColumns: "2fr 1fr",
    gap: 12,
  },
  btn: {
    padding: "14px 32px",
    borderRadius: "10px",
    border: "none",
    fontSize: 16,
    fontWeight: 600,
    color: "#fff",
    background: "linear-gradient(135deg, var(--accent) 0%, var(--accent-dark) 100%)",
    cursor: "pointer",
    transition: "all 0.3s ease",
    boxShadow: "0 4px 12px rgba(170, 59, 255, 0.3)",
    outline: "none",
  },
  btnHover: {
    background: "linear-gradient(135deg, var(--accent-dark) 0%, var(--accent) 100%)",
    boxShadow: "0 8px 24px rgba(170, 59, 255, 0.4)",
    transform: "translateY(-2px)",
  },
  btnDisabled: {
    opacity: 0.6,
    cursor: "not-allowed",
    boxShadow: "0 2px 8px rgba(0, 0, 0, 0.1)",
  },
  resultCard: {
    background: "linear-gradient(135deg, var(--accent-bg) 0%, rgba(192, 132, 252, 0.05) 100%)",
    border: "1.5px solid var(--accent-border)",
    borderRadius: "12px",
    padding: "24px",
    textAlign: "center",
    marginTop: 12,
  },
  badge: {
    display: "inline-block",
    background: "var(--accent)",
    color: "#fff",
    padding: "6px 12px",
    borderRadius: "20px",
    fontSize: 12,
    fontWeight: 600,
    letterSpacing: "0.05em",
    textTransform: "uppercase",
  },
};
